(in-package :dxf)

(defclass <acad-p-viewport> (<acad-entity>)
  (
  (ac-application              :accessor ac-application              :initarg :ac-application              :initform nil :documentation "ac-application")
  (ac-arc-smoothness           :accessor ac-arc-smoothness           :initarg :ac-arc-smoothness           :initform nil :documentation "ac-arc-smoothness")
  (ac-center                   :accessor ac-center                   :initarg :ac-center                   :initform nil :documentation "ac-center")
  (ac-clipped                  :accessor ac-clipped                  :initarg :ac-clipped                  :initform nil :documentation "ac-clipped")
  (ac-custom-scale             :accessor ac-custom-scale             :initarg :ac-custom-scale             :initform nil :documentation "ac-custom-scale")
  (ac-direction                :accessor ac-direction                :initarg :ac-direction                :initform nil :documentation "ac-direction")
  (ac-display-locked           :accessor ac-display-locked           :initarg :ac-display-locked           :initform nil :documentation "ac-display-locked")
  (ac-document                 :accessor ac-document                 :initarg :ac-document                 :initform nil :documentation "ac-document")
  (ac-entity-transparency      :accessor ac-entity-transparency      :initarg :ac-entity-transparency      :initform nil :documentation "ac-entity-transparency")
  (ac-grid-on                  :accessor ac-grid-on                  :initarg :ac-grid-on                  :initform nil :documentation "ac-grid-on")
  (ac-handle                   :accessor ac-handle                   :initarg :ac-handle                   :initform nil :documentation "ac-handle")
  (ac-has-extension-dictionary :accessor ac-has-extension-dictionary :initarg :ac-has-extension-dictionary :initform nil :documentation "ac-has-extension-dictionary")
  (ac-has-sheet-view           :accessor ac-has-sheet-view           :initarg :ac-has-sheet-view           :initform nil :documentation "ac-has-sheet-view")
  (ac-height                   :accessor ac-height                   :initarg :ac-height                   :initform nil :documentation "ac-height")
  (ac-hyperlinks               :accessor ac-hyperlinks               :initarg :ac-hyperlinks               :initform nil :documentation "ac-hyperlinks")
  (ac-label-block-id           :accessor ac-label-block-id           :initarg :ac-label-block-id           :initform nil :documentation "ac-label-block-id")
  (ac-layer                    :accessor ac-layer                    :initarg :ac-layer                    :initform nil :documentation "ac-layer")
  (ac-layer-property-overrides :accessor ac-layer-property-overrides :initarg :ac-layer-property-overrides :initform nil :documentation "ac-layer-property-overrides")
  (ac-lens-length              :accessor ac-lens-length              :initarg :ac-lens-length              :initform nil :documentation "ac-lens-length")
  (ac-linetype                 :accessor ac-linetype                 :initarg :ac-linetype                 :initform nil :documentation "ac-linetype")
  (ac-linetype-scale           :accessor ac-linetype-scale           :initarg :ac-linetype-scale           :initform nil :documentation "ac-linetype-scale")
  (ac-lineweight               :accessor ac-lineweight               :initarg :ac-lineweight               :initform nil :documentation "ac-lineweight")
  (ac-material                 :accessor ac-material                 :initarg :ac-material                 :initform nil :documentation "ac-material")
  (ac-model-view               :accessor ac-model-view               :initarg :ac-model-view               :initform nil :documentation "ac-model-view")
  (ac-object-id                :accessor ac-object-id                :initarg :ac-object-id                :initform nil :documentation "ac-object-id")
  (ac-object-name              :accessor ac-object-name              :initarg :ac-object-name              :initform nil :documentation "ac-object-name")
  (ac-owner-id                 :accessor ac-owner-id                 :initarg :ac-owner-id                 :initform nil :documentation "ac-owner-id")
  (ac-plot-style-name          :accessor ac-plot-style-name          :initarg :ac-plot-style-name          :initform nil :documentation "ac-plot-style-name")
  (ac-shade-plot               :accessor ac-shade-plot               :initarg :ac-shade-plot               :initform nil :documentation "ac-shade-plot")
  (ac-sheet-view               :accessor ac-sheet-view               :initarg :ac-sheet-view               :initform nil :documentation "ac-sheet-view")
  (ac-snap-base-point          :accessor ac-snap-base-point          :initarg :ac-snap-base-point          :initform nil :documentation "ac-snap-base-point")
  (ac-snap-on                  :accessor ac-snap-on                  :initarg :ac-snap-on                  :initform nil :documentation "ac-snap-on")
  (ac-snap-rotation-angle      :accessor ac-snap-rotation-angle      :initarg :ac-snap-rotation-angle      :initform nil :documentation "ac-snap-rotation-angle")
  (ac-standard-scale           :accessor ac-standard-scale           :initarg :ac-standard-scale           :initform nil :documentation "ac-standard-scale")
  (ac-standard-scale2          :accessor ac-standard-scale2          :initarg :ac-standard-scale2          :initform nil :documentation "ac-standard-scale2")
  (ac-target                   :accessor ac-target                   :initarg :ac-target                   :initform nil :documentation "ac-target")
  (ac-true-color               :accessor ac-true-color               :initarg :ac-true-color               :initform nil :documentation "ac-true-color")
  (ac-twist-angle              :accessor ac-twist-angle              :initarg :ac-twist-angle              :initform nil :documentation "ac-twist-angle")
  (ac-ucs-icon-at-origin       :accessor ac-ucs-icon-at-origin       :initarg :ac-ucs-icon-at-origin       :initform nil :documentation "ac-ucs-icon-at-origin")
  (ac-ucs-icon-on              :accessor ac-ucs-icon-on              :initarg :ac-ucs-icon-on              :initform nil :documentation "ac-ucs-icon-on")
  (ac-ucs-per-viewport         :accessor ac-ucs-per-viewport         :initarg :ac-ucs-per-viewport         :initform nil :documentation "ac-ucs-per-viewport")
  (ac-viewport-on              :accessor ac-viewport-on              :initarg :ac-viewport-on              :initform nil :documentation "ac-viewport-on")
  (ac-visible                  :accessor ac-visible                  :initarg :ac-visible                  :initform nil :documentation "ac-visible")
  (ac-visual-style             :accessor ac-visual-style             :initarg :ac-visual-style             :initform nil :documentation "ac-visual-style")
  (ac-width                    :accessor ac-width                    :initarg :ac-width                    :initform nil :documentation "ac-width")
  )
  (:documentation "Rectangular objects created in paper space that display views."))

(defparameter *acad-p-viewport-properties* '(ac-application ac-arc-smoothness ac-center ac-clipped ac-custom-scale ac-direction ac-display-locked ac-document ac-entity-transparency ac-grid-on ac-handle ac-has-extension-dictionary ac-has-sheet-view ac-height ac-hyperlinks ac-label-block-id ac-layer ac-layer-property-overrides ac-lens-length ac-linetype ac-linetype-scale ac-lineweight ac-material ac-model-view ac-object-id ac-object-name ac-owner-id ac-plot-style-name ac-shade-plot ac-sheet-view ac-snap-base-point ac-snap-on ac-snap-rotation-angle ac-standard-scale ac-standard-scale2 ac-target ac-true-color ac-twist-angle ac-ucs-icon-at-origin ac-ucs-icon-on ac-ucs-per-viewport ac-viewport-on ac-visible ac-visual-style ac-width))

(mapcar #'dxf/utils:make-slot (set-difference *acad-p-viewport-properties* *acad-entity-properties*))
