(in-package :dxf)

(defclass <acad-m-leader> (<acad-entity>)
  (
  (ac-application              :accessor ac-application              :initarg :ac-application              :initform nil :documentation "ac-application")
  (ac-arrowhead-block          :accessor ac-arrowhead-block          :initarg :ac-arrowhead-block          :initform nil :documentation "ac-arrowhead-block")
  (ac-arrowhead-size           :accessor ac-arrowhead-size           :initarg :ac-arrowhead-size           :initform nil :documentation "ac-arrowhead-size")
  (ac-arrowhead-type           :accessor ac-arrowhead-type           :initarg :ac-arrowhead-type           :initform nil :documentation "ac-arrowhead-type")
  (ac-block-connection-type    :accessor ac-block-connection-type    :initarg :ac-block-connection-type    :initform nil :documentation "ac-block-connection-type")
  (ac-block-scale              :accessor ac-block-scale              :initarg :ac-block-scale              :initform nil :documentation "ac-block-scale")
  (ac-content-block-name       :accessor ac-content-block-name       :initarg :ac-content-block-name       :initform nil :documentation "ac-content-block-name")
  (ac-content-block-type       :accessor ac-content-block-type       :initarg :ac-content-block-type       :initform nil :documentation "ac-content-block-type")
  (ac-content-type             :accessor ac-content-type             :initarg :ac-content-type             :initform nil :documentation "ac-content-type")
  (ac-document                 :accessor ac-document                 :initarg :ac-document                 :initform nil :documentation "ac-document")
  (ac-dog-legged               :accessor ac-dog-legged               :initarg :ac-dog-legged               :initform nil :documentation "ac-dog-legged")
  (ac-dogleg-length            :accessor ac-dogleg-length            :initarg :ac-dogleg-length            :initform nil :documentation "ac-dogleg-length")
  (ac-entity-transparency      :accessor ac-entity-transparency      :initarg :ac-entity-transparency      :initform nil :documentation "ac-entity-transparency")
  (ac-handle                   :accessor ac-handle                   :initarg :ac-handle                   :initform nil :documentation "ac-handle")
  (ac-has-extension-dictionary :accessor ac-has-extension-dictionary :initarg :ac-has-extension-dictionary :initform nil :documentation "ac-has-extension-dictionary")
  (ac-hyperlinks               :accessor ac-hyperlinks               :initarg :ac-hyperlinks               :initform nil :documentation "ac-hyperlinks")
  (ac-landing-gap              :accessor ac-landing-gap              :initarg :ac-landing-gap              :initform nil :documentation "ac-landing-gap")
  (ac-layer                    :accessor ac-layer                    :initarg :ac-layer                    :initform nil :documentation "ac-layer")
  (ac-leader-count             :accessor ac-leader-count             :initarg :ac-leader-count             :initform nil :documentation "ac-leader-count")
  (ac-leader-line-color        :accessor ac-leader-line-color        :initarg :ac-leader-line-color        :initform nil :documentation "ac-leader-line-color")
  (ac-leader-line-type         :accessor ac-leader-line-type         :initarg :ac-leader-line-type         :initform nil :documentation "ac-leader-line-type")
  (ac-leader-line-weight       :accessor ac-leader-line-weight       :initarg :ac-leader-line-weight       :initform nil :documentation "ac-leader-line-weight")
  (ac-leader-type              :accessor ac-leader-type              :initarg :ac-leader-type              :initform nil :documentation "ac-leader-type")
  (ac-linetype                 :accessor ac-linetype                 :initarg :ac-linetype                 :initform nil :documentation "ac-linetype")
  (ac-linetype-scale           :accessor ac-linetype-scale           :initarg :ac-linetype-scale           :initform nil :documentation "ac-linetype-scale")
  (ac-lineweight               :accessor ac-lineweight               :initarg :ac-lineweight               :initform nil :documentation "ac-lineweight")
  (ac-material                 :accessor ac-material                 :initarg :ac-material                 :initform nil :documentation "ac-material")
  (ac-normal                   :accessor ac-normal                   :initarg :ac-normal                   :initform nil :documentation "ac-normal")
  (ac-object-id                :accessor ac-object-id                :initarg :ac-object-id                :initform nil :documentation "ac-object-id")
  (ac-object-name              :accessor ac-object-name              :initarg :ac-object-name              :initform nil :documentation "ac-object-name")
  (ac-owner-id                 :accessor ac-owner-id                 :initarg :ac-owner-id                 :initform nil :documentation "ac-owner-id")
  (ac-plot-style-name          :accessor ac-plot-style-name          :initarg :ac-plot-style-name          :initform nil :documentation "ac-plot-style-name")
  (ac-scale-factor             :accessor ac-scale-factor             :initarg :ac-scale-factor             :initform nil :documentation "ac-scale-factor")
  (ac-style-name               :accessor ac-style-name               :initarg :ac-style-name               :initform nil :documentation "ac-style-name")
  (ac-text-attachment-direction :accessor ac-text-attachment-direction :initarg :ac-text-attachment-direction :initform nil :documentation "ac-text-attachment-direction")
  (ac-text-background-fill     :accessor ac-text-background-fill     :initarg :ac-text-background-fill     :initform nil :documentation "ac-text-background-fill")
  (ac-text-bottom-attachment-type :accessor ac-text-bottom-attachment-type :initarg :ac-text-bottom-attachment-type :initform nil :documentation "ac-text-bottom-attachment-type")
  (ac-text-direction           :accessor ac-text-direction           :initarg :ac-text-direction           :initform nil :documentation "ac-text-direction")
  (ac-text-frame-display       :accessor ac-text-frame-display       :initarg :ac-text-frame-display       :initform nil :documentation "ac-text-frame-display")
  (ac-text-height              :accessor ac-text-height              :initarg :ac-text-height              :initform nil :documentation "ac-text-height")
  (ac-text-justify             :accessor ac-text-justify             :initarg :ac-text-justify             :initform nil :documentation "ac-text-justify")
  (ac-text-left-attachment-type :accessor ac-text-left-attachment-type :initarg :ac-text-left-attachment-type :initform nil :documentation "ac-text-left-attachment-type")
  (ac-text-line-spacing-distance :accessor ac-text-line-spacing-distance :initarg :ac-text-line-spacing-distance :initform nil :documentation "ac-text-line-spacing-distance")
  (ac-text-line-spacing-factor :accessor ac-text-line-spacing-factor :initarg :ac-text-line-spacing-factor :initform nil :documentation "ac-text-line-spacing-factor")
  (ac-text-line-spacing-style  :accessor ac-text-line-spacing-style  :initarg :ac-text-line-spacing-style  :initform nil :documentation "ac-text-line-spacing-style")
  (ac-text-right-attachment-type :accessor ac-text-right-attachment-type :initarg :ac-text-right-attachment-type :initform nil :documentation "ac-text-right-attachment-type")
  (ac-text-rotation            :accessor ac-text-rotation            :initarg :ac-text-rotation            :initform nil :documentation "ac-text-rotation")
  (ac-text-string              :accessor ac-text-string              :initarg :ac-text-string              :initform nil :documentation "ac-text-string")
  (ac-text-style-name          :accessor ac-text-style-name          :initarg :ac-text-style-name          :initform nil :documentation "ac-text-style-name")
  (ac-text-top-attachment-type :accessor ac-text-top-attachment-type :initarg :ac-text-top-attachment-type :initform nil :documentation "ac-text-top-attachment-type")
  (ac-text-width               :accessor ac-text-width               :initarg :ac-text-width               :initform nil :documentation "ac-text-width")
  (ac-true-color               :accessor ac-true-color               :initarg :ac-true-color               :initform nil :documentation "ac-true-color")
  (ac-type                     :accessor ac-type                     :initarg :ac-type                     :initform nil :documentation "ac-type")
  (ac-visible                  :accessor ac-visible                  :initarg :ac-visible                  :initform nil :documentation "ac-visible")
  )
  (:documentation "An object composed of an arrowhead attached to multiple splines or straight line segments."))

(defparameter *acad-m-leader-properties* '(ac-application ac-arrowhead-block ac-arrowhead-size ac-arrowhead-type ac-block-connection-type ac-block-scale ac-content-block-name ac-content-block-type ac-content-type ac-document ac-dog-legged ac-dogleg-length ac-entity-transparency ac-handle ac-has-extension-dictionary ac-hyperlinks ac-landing-gap ac-layer ac-leader-count ac-leader-line-color ac-leader-line-type ac-leader-line-weight ac-leader-type ac-linetype ac-linetype-scale ac-lineweight ac-material ac-normal ac-object-id ac-object-name ac-owner-id ac-plot-style-name ac-scale-factor ac-style-name ac-text-attachment-direction ac-text-background-fill ac-text-bottom-attachment-type ac-text-direction ac-text-frame-display ac-text-height ac-text-justify ac-text-left-attachment-type ac-text-line-spacing-distance ac-text-line-spacing-factor ac-text-line-spacing-style ac-text-right-attachment-type ac-text-rotation ac-text-string ac-text-style-name ac-text-top-attachment-type ac-text-width ac-true-color ac-type ac-visible))

(mapcar #'dxf/utils:make-slot (set-difference *acad-m-leader-properties* *acad-entity-properties*))
