(in-package :dxf)

(defclass <acad-point-cloud-ex> (<acad-entity>)
  (
  (ac-application              :accessor ac-application              :initarg :ac-application              :initform nil :documentation "ac-application")
  (ac-color-scheme             :accessor ac-color-scheme             :initarg :ac-color-scheme             :initform nil :documentation "ac-color-scheme")
  (ac-document                 :accessor ac-document                 :initarg :ac-document                 :initform nil :documentation "ac-document")
  (ac-entity-transparency      :accessor ac-entity-transparency      :initarg :ac-entity-transparency      :initform nil :documentation "ac-entity-transparency")
  (ac-geolocate                :accessor ac-geolocate                :initarg :ac-geolocate                :initform nil :documentation "ac-geolocate")
  (ac-handle                   :accessor ac-handle                   :initarg :ac-handle                   :initform nil :documentation "ac-handle")
  (ac-has-extension-dictionary :accessor ac-has-extension-dictionary :initarg :ac-has-extension-dictionary :initform nil :documentation "ac-has-extension-dictionary")
  (ac-hyperlinks               :accessor ac-hyperlinks               :initarg :ac-hyperlinks               :initform nil :documentation "ac-hyperlinks")
  (ac-insertion-point          :accessor ac-insertion-point          :initarg :ac-insertion-point          :initform nil :documentation "ac-insertion-point")
  (ac-layer                    :accessor ac-layer                    :initarg :ac-layer                    :initform nil :documentation "ac-layer")
  (ac-linetype                 :accessor ac-linetype                 :initarg :ac-linetype                 :initform nil :documentation "ac-linetype")
  (ac-linetype-scale           :accessor ac-linetype-scale           :initarg :ac-linetype-scale           :initform nil :documentation "ac-linetype-scale")
  (ac-lineweight               :accessor ac-lineweight               :initarg :ac-lineweight               :initform nil :documentation "ac-lineweight")
  (ac-locked                   :accessor ac-locked                   :initarg :ac-locked                   :initform nil :documentation "ac-locked")
  (ac-material                 :accessor ac-material                 :initarg :ac-material                 :initform nil :documentation "ac-material")
  (ac-name                     :accessor ac-name                     :initarg :ac-name                     :initform nil :documentation "ac-name")
  (ac-object-id                :accessor ac-object-id                :initarg :ac-object-id                :initform nil :documentation "ac-object-id")
  (ac-object-name              :accessor ac-object-name              :initarg :ac-object-name              :initform nil :documentation "ac-object-name")
  (ac-owner-id                 :accessor ac-owner-id                 :initarg :ac-owner-id                 :initform nil :documentation "ac-owner-id")
  (ac-path                     :accessor ac-path                     :initarg :ac-path                     :initform nil :documentation "ac-path")
  (ac-plot-style-name          :accessor ac-plot-style-name          :initarg :ac-plot-style-name          :initform nil :documentation "ac-plot-style-name")
  (ac-rotation                 :accessor ac-rotation                 :initarg :ac-rotation                 :initform nil :documentation "ac-rotation")
  (ac-scale                    :accessor ac-scale                    :initarg :ac-scale                    :initform nil :documentation "ac-scale")
  (ac-segmentation             :accessor ac-segmentation             :initarg :ac-segmentation             :initform nil :documentation "ac-segmentation")
  (ac-show-cropped             :accessor ac-show-cropped             :initarg :ac-show-cropped             :initform nil :documentation "ac-show-cropped")
  (ac-stylization              :accessor ac-stylization              :initarg :ac-stylization              :initform nil :documentation "ac-stylization")
  (ac-true-color               :accessor ac-true-color               :initarg :ac-true-color               :initform nil :documentation "ac-true-color")
  (ac-unit                     :accessor ac-unit                     :initarg :ac-unit                     :initform nil :documentation "ac-unit")
  (ac-unit-factor              :accessor ac-unit-factor              :initarg :ac-unit-factor              :initform nil :documentation "ac-unit-factor")
  (ac-visible                  :accessor ac-visible                  :initarg :ac-visible                  :initform nil :documentation "ac-visible")
  )
  (:documentation "A point cloud extension entity."))

(defparameter *acad-point-cloud-ex-properties* '(ac-application ac-color-scheme ac-document ac-entity-transparency ac-geolocate ac-handle ac-has-extension-dictionary ac-hyperlinks ac-insertion-point ac-layer ac-linetype ac-linetype-scale ac-lineweight ac-locked ac-material ac-name ac-object-id ac-object-name ac-owner-id ac-path ac-plot-style-name ac-rotation ac-scale ac-segmentation ac-show-cropped ac-stylization ac-true-color ac-unit ac-unit-factor ac-visible))

(mapcar #'dxf/utils:make-slot (set-difference *acad-point-cloud-ex-properties* *acad-entity-properties*))
