(in-package :dxf)

(defclass <acad-ellipse> (<acad-entity>)
  (
  (ac-application              :accessor ac-application              :initarg :ac-application              :initform nil :documentation "ac-application")
  (ac-area                     :accessor ac-area                     :initarg :ac-area                     :initform nil :documentation "ac-area")
  (ac-center                   :accessor ac-center                   :initarg :ac-center                   :initform nil :documentation "ac-center")
  (ac-document                 :accessor ac-document                 :initarg :ac-document                 :initform nil :documentation "ac-document")
  (ac-end-angle                :accessor ac-end-angle                :initarg :ac-end-angle                :initform nil :documentation "ac-end-angle")
  (ac-end-parameter            :accessor ac-end-parameter            :initarg :ac-end-parameter            :initform nil :documentation "ac-end-parameter")
  (ac-end-point                :accessor ac-end-point                :initarg :ac-end-point                :initform nil :documentation "ac-end-point")
  (ac-entity-transparency      :accessor ac-entity-transparency      :initarg :ac-entity-transparency      :initform nil :documentation "ac-entity-transparency")
  (ac-handle                   :accessor ac-handle                   :initarg :ac-handle                   :initform nil :documentation "ac-handle")
  (ac-has-extension-dictionary :accessor ac-has-extension-dictionary :initarg :ac-has-extension-dictionary :initform nil :documentation "ac-has-extension-dictionary")
  (ac-hyperlinks               :accessor ac-hyperlinks               :initarg :ac-hyperlinks               :initform nil :documentation "ac-hyperlinks")
  (ac-layer                    :accessor ac-layer                    :initarg :ac-layer                    :initform nil :documentation "ac-layer")
  (ac-linetype                 :accessor ac-linetype                 :initarg :ac-linetype                 :initform nil :documentation "ac-linetype")
  (ac-linetype-scale           :accessor ac-linetype-scale           :initarg :ac-linetype-scale           :initform nil :documentation "ac-linetype-scale")
  (ac-lineweight               :accessor ac-lineweight               :initarg :ac-lineweight               :initform nil :documentation "ac-lineweight")
  (ac-major-axis               :accessor ac-major-axis               :initarg :ac-major-axis               :initform nil :documentation "ac-major-axis")
  (ac-major-radius             :accessor ac-major-radius             :initarg :ac-major-radius             :initform nil :documentation "ac-major-radius")
  (ac-material                 :accessor ac-material                 :initarg :ac-material                 :initform nil :documentation "ac-material")
  (ac-minor-axis               :accessor ac-minor-axis               :initarg :ac-minor-axis               :initform nil :documentation "ac-minor-axis")
  (ac-minor-radius             :accessor ac-minor-radius             :initarg :ac-minor-radius             :initform nil :documentation "ac-minor-radius")
  (ac-normal                   :accessor ac-normal                   :initarg :ac-normal                   :initform nil :documentation "ac-normal")
  (ac-object-id                :accessor ac-object-id                :initarg :ac-object-id                :initform nil :documentation "ac-object-id")
  (ac-object-name              :accessor ac-object-name              :initarg :ac-object-name              :initform nil :documentation "ac-object-name")
  (ac-owner-id                 :accessor ac-owner-id                 :initarg :ac-owner-id                 :initform nil :documentation "ac-owner-id")
  (ac-plot-style-name          :accessor ac-plot-style-name          :initarg :ac-plot-style-name          :initform nil :documentation "ac-plot-style-name")
  (ac-radius-ratio             :accessor ac-radius-ratio             :initarg :ac-radius-ratio             :initform nil :documentation "ac-radius-ratio")
  (ac-start-angle              :accessor ac-start-angle              :initarg :ac-start-angle              :initform nil :documentation "ac-start-angle")
  (ac-start-parameter          :accessor ac-start-parameter          :initarg :ac-start-parameter          :initform nil :documentation "ac-start-parameter")
  (ac-start-point              :accessor ac-start-point              :initarg :ac-start-point              :initform nil :documentation "ac-start-point")
  (ac-true-color               :accessor ac-true-color               :initarg :ac-true-color               :initform nil :documentation "ac-true-color")
  (ac-visible                  :accessor ac-visible                  :initarg :ac-visible                  :initform nil :documentation "ac-visible")
  )
  (:documentation "An elliptical arc or full ellipse."))

(defparameter *acad-ellipse-properties* '(ac-application ac-area ac-center ac-document ac-end-angle ac-end-parameter ac-end-point ac-entity-transparency ac-handle ac-has-extension-dictionary ac-hyperlinks ac-layer ac-linetype ac-linetype-scale ac-lineweight ac-major-axis ac-major-radius ac-material ac-minor-axis ac-minor-radius ac-normal ac-object-id ac-object-name ac-owner-id ac-plot-style-name ac-radius-ratio ac-start-angle ac-start-parameter ac-start-point ac-true-color ac-visible))

(mapcar #'dxf/utils:make-slot (set-difference *acad-ellipse-properties* *acad-entity-properties*))
