(in-package :dxf)

(defclass <acad-leader> (<acad-entity>)
  (
  (pr-annotation               :accessor pr-annotation               :initarg :pr-annotation               :initform nil :documentation "pr-annotation")
  (pr-application              :accessor pr-application              :initarg :pr-application              :initform nil :documentation "pr-application")
  (pr-arrowhead-block          :accessor pr-arrowhead-block          :initarg :pr-arrowhead-block          :initform nil :documentation "pr-arrowhead-block")
  (pr-arrowhead-size           :accessor pr-arrowhead-size           :initarg :pr-arrowhead-size           :initform nil :documentation "pr-arrowhead-size")
  (pr-arrowhead-type           :accessor pr-arrowhead-type           :initarg :pr-arrowhead-type           :initform nil :documentation "pr-arrowhead-type")
  (pr-coordinate               :accessor pr-coordinate               :initarg :pr-coordinate               :initform nil :documentation "pr-coordinate")
  (pr-coordinates              :accessor pr-coordinates              :initarg :pr-coordinates              :initform nil :documentation "pr-coordinates")
  (pr-dimension-line-color     :accessor pr-dimension-line-color     :initarg :pr-dimension-line-color     :initform nil :documentation "pr-dimension-line-color")
  (pr-dimension-line-weight    :accessor pr-dimension-line-weight    :initarg :pr-dimension-line-weight    :initform nil :documentation "pr-dimension-line-weight")
  (pr-document                 :accessor pr-document                 :initarg :pr-document                 :initform nil :documentation "pr-document")
  (pr-entity-transparency      :accessor pr-entity-transparency      :initarg :pr-entity-transparency      :initform nil :documentation "pr-entity-transparency")
  (pr-handle                   :accessor pr-handle                   :initarg :pr-handle                   :initform nil :documentation "pr-handle")
  (pr-has-extension-dictionary :accessor pr-has-extension-dictionary :initarg :pr-has-extension-dictionary :initform nil :documentation "pr-has-extension-dictionary")
  (pr-hyperlinks               :accessor pr-hyperlinks               :initarg :pr-hyperlinks               :initform nil :documentation "pr-hyperlinks")
  (pr-layer                    :accessor pr-layer                    :initarg :pr-layer                    :initform nil :documentation "pr-layer")
  (pr-linetype                 :accessor pr-linetype                 :initarg :pr-linetype                 :initform nil :documentation "pr-linetype")
  (pr-linetype-scale           :accessor pr-linetype-scale           :initarg :pr-linetype-scale           :initform nil :documentation "pr-linetype-scale")
  (pr-lineweight               :accessor pr-lineweight               :initarg :pr-lineweight               :initform nil :documentation "pr-lineweight")
  (pr-material                 :accessor pr-material                 :initarg :pr-material                 :initform nil :documentation "pr-material")
  (pr-normal                   :accessor pr-normal                   :initarg :pr-normal                   :initform nil :documentation "pr-normal")
  (pr-object-id                :accessor pr-object-id                :initarg :pr-object-id                :initform nil :documentation "pr-object-id")
  (pr-object-name              :accessor pr-object-name              :initarg :pr-object-name              :initform nil :documentation "pr-object-name")
  (pr-owner-id                 :accessor pr-owner-id                 :initarg :pr-owner-id                 :initform nil :documentation "pr-owner-id")
  (pr-plot-style-name          :accessor pr-plot-style-name          :initarg :pr-plot-style-name          :initform nil :documentation "pr-plot-style-name")
  (pr-scale-factor             :accessor pr-scale-factor             :initarg :pr-scale-factor             :initform nil :documentation "pr-scale-factor")
  (pr-style-name               :accessor pr-style-name               :initarg :pr-style-name               :initform nil :documentation "pr-style-name")
  (pr-text-gap                 :accessor pr-text-gap                 :initarg :pr-text-gap                 :initform nil :documentation "pr-text-gap")
  (pr-true-color               :accessor pr-true-color               :initarg :pr-true-color               :initform nil :documentation "pr-true-color")
  (pr-type                     :accessor pr-type                     :initarg :pr-type                     :initform nil :documentation "pr-type")
  (pr-vertical-text-position   :accessor pr-vertical-text-position   :initarg :pr-vertical-text-position   :initform nil :documentation "pr-vertical-text-position")
  (pr-visible                  :accessor pr-visible                  :initarg :pr-visible                  :initform nil :documentation "pr-visible")
  )
  (:documentation "
@link[uri=\"https://help.autodesk.com/view/ACD/2022/RUS/?guid=GUID-E1EC4A71-6FC0-4B76-AD53-4DE561D6EE46\"](Leader Object (ActiveX))"))

(defparameter *acad-leader-properties* '(pr-annotation pr-application pr-arrowhead-block pr-arrowhead-size pr-arrowhead-type pr-coordinate pr-coordinates pr-dimension-line-color pr-dimension-line-weight pr-document pr-entity-transparency pr-handle pr-has-extension-dictionary pr-hyperlinks pr-layer pr-linetype pr-linetype-scale pr-lineweight pr-material pr-normal pr-object-id pr-object-name pr-owner-id pr-plot-style-name pr-scale-factor pr-style-name pr-text-gap pr-true-color pr-type pr-vertical-text-position pr-visible))

(mapcar #'dxf/utils:make-slot (set-difference *acad-leader-properties* *acad-entity-properties*))
