(in-package :dxf)

(defclass <acad-ole> (<acad-entity>)
  (
  (ac-application              :accessor ac-application              :initarg :ac-application              :initform nil :documentation "ac-application")
  (ac-document                 :accessor ac-document                 :initarg :ac-document                 :initform nil :documentation "ac-document")
  (ac-entity-transparency      :accessor ac-entity-transparency      :initarg :ac-entity-transparency      :initform nil :documentation "ac-entity-transparency")
  (ac-handle                   :accessor ac-handle                   :initarg :ac-handle                   :initform nil :documentation "ac-handle")
  (ac-has-extension-dictionary :accessor ac-has-extension-dictionary :initarg :ac-has-extension-dictionary :initform nil :documentation "ac-has-extension-dictionary")
  (ac-height                   :accessor ac-height                   :initarg :ac-height                   :initform nil :documentation "ac-height")
  (ac-hyperlinks               :accessor ac-hyperlinks               :initarg :ac-hyperlinks               :initform nil :documentation "ac-hyperlinks")
  (ac-insertion-point          :accessor ac-insertion-point          :initarg :ac-insertion-point          :initform nil :documentation "ac-insertion-point")
  (ac-layer                    :accessor ac-layer                    :initarg :ac-layer                    :initform nil :documentation "ac-layer")
  (ac-linetype                 :accessor ac-linetype                 :initarg :ac-linetype                 :initform nil :documentation "ac-linetype")
  (ac-linetype-scale           :accessor ac-linetype-scale           :initarg :ac-linetype-scale           :initform nil :documentation "ac-linetype-scale")
  (ac-lineweight               :accessor ac-lineweight               :initarg :ac-lineweight               :initform nil :documentation "ac-lineweight")
  (ac-lock-aspect-ratio        :accessor ac-lock-aspect-ratio        :initarg :ac-lock-aspect-ratio        :initform nil :documentation "ac-lock-aspect-ratio")
  (ac-material                 :accessor ac-material                 :initarg :ac-material                 :initform nil :documentation "ac-material")
  (ac-object-id                :accessor ac-object-id                :initarg :ac-object-id                :initform nil :documentation "ac-object-id")
  (ac-object-name              :accessor ac-object-name              :initarg :ac-object-name              :initform nil :documentation "ac-object-name")
  (ac-ole-item-type            :accessor ac-ole-item-type            :initarg :ac-ole-item-type            :initform nil :documentation "ac-ole-item-type")
  (ac-ole-plot-quality         :accessor ac-ole-plot-quality         :initarg :ac-ole-plot-quality         :initform nil :documentation "ac-ole-plot-quality")
  (ac-ole-source-app           :accessor ac-ole-source-app           :initarg :ac-ole-source-app           :initform nil :documentation "ac-ole-source-app")
  (ac-owner-id                 :accessor ac-owner-id                 :initarg :ac-owner-id                 :initform nil :documentation "ac-owner-id")
  (ac-plot-style-name          :accessor ac-plot-style-name          :initarg :ac-plot-style-name          :initform nil :documentation "ac-plot-style-name")
  (ac-rotation                 :accessor ac-rotation                 :initarg :ac-rotation                 :initform nil :documentation "ac-rotation")
  (ac-scale-height             :accessor ac-scale-height             :initarg :ac-scale-height             :initform nil :documentation "ac-scale-height")
  (ac-scale-width              :accessor ac-scale-width              :initarg :ac-scale-width              :initform nil :documentation "ac-scale-width")
  (ac-true-color               :accessor ac-true-color               :initarg :ac-true-color               :initform nil :documentation "ac-true-color")
  (ac-visible                  :accessor ac-visible                  :initarg :ac-visible                  :initform nil :documentation "ac-visible")
  (ac-width                    :accessor ac-width                    :initarg :ac-width                    :initform nil :documentation "ac-width")
  )
  (:documentation "An AutoCAD OLE object."))

(defparameter *acad-ole-properties* '(ac-application ac-document ac-entity-transparency ac-handle ac-has-extension-dictionary ac-height ac-hyperlinks ac-insertion-point ac-layer ac-linetype ac-linetype-scale ac-lineweight ac-lock-aspect-ratio ac-material ac-object-id ac-object-name ac-ole-item-type ac-ole-plot-quality ac-ole-source-app ac-owner-id ac-plot-style-name ac-rotation ac-scale-height ac-scale-width ac-true-color ac-visible ac-width))

(mapcar #'dxf/utils:make-slot (set-difference *acad-ole-properties* *acad-entity-properties*))
