(defclass <acad-layer> (<acad-object>)
  (
  (ac-application              :accessor ac-application              :initarg :ac-application              :initform nil :documentation "ac-application")
  (ac-description              :accessor ac-description              :initarg :ac-description              :initform nil :documentation "ac-description")
  (ac-document                 :accessor ac-document                 :initarg :ac-document                 :initform nil :documentation "ac-document")
  (ac-freeze                   :accessor ac-freeze                   :initarg :ac-freeze                   :initform nil :documentation "ac-freeze")
  (ac-handle                   :accessor ac-handle                   :initarg :ac-handle                   :initform nil :documentation "ac-handle")
  (ac-has-extension-dictionary :accessor ac-has-extension-dictionary :initarg :ac-has-extension-dictionary :initform nil :documentation "ac-has-extension-dictionary")
  (ac-layer-on                 :accessor ac-layer-on                 :initarg :ac-layer-on                 :initform nil :documentation "ac-layer-on")
  (ac-linetype                 :accessor ac-linetype                 :initarg :ac-linetype                 :initform nil :documentation "ac-linetype")
  (ac-lineweight               :accessor ac-lineweight               :initarg :ac-lineweight               :initform nil :documentation "ac-lineweight")
  (ac-lock                     :accessor ac-lock                     :initarg :ac-lock                     :initform nil :documentation "ac-lock")
  (ac-material                 :accessor ac-material                 :initarg :ac-material                 :initform nil :documentation "ac-material")
  (ac-name                     :accessor ac-name                     :initarg :ac-name                     :initform nil :documentation "ac-name")
  (ac-object-id                :accessor ac-object-id                :initarg :ac-object-id                :initform nil :documentation "ac-object-id")
  (ac-object-name              :accessor ac-object-name              :initarg :ac-object-name              :initform nil :documentation "ac-object-name")
  (ac-owner-id                 :accessor ac-owner-id                 :initarg :ac-owner-id                 :initform nil :documentation "ac-owner-id")
  (ac-plot-style-name          :accessor ac-plot-style-name          :initarg :ac-plot-style-name          :initform nil :documentation "ac-plot-style-name")
  (ac-plottable                :accessor ac-plottable                :initarg :ac-plottable                :initform nil :documentation "ac-plottable")
  (ac-true-color               :accessor ac-true-color               :initarg :ac-true-color               :initform nil :documentation "ac-true-color")
  (ac-used                     :accessor ac-used                     :initarg :ac-used                     :initform nil :documentation "ac-used")
  (ac-viewport-default         :accessor ac-viewport-default         :initarg :ac-viewport-default         :initform nil :documentation "ac-viewport-default")
  )
  (:documentation "A logical grouping of data, similar to transparent acetate overlays on a drawing."))

(defparameter *acad-layer-properties* '(ac-application ac-description ac-document ac-freeze ac-handle ac-has-extension-dictionary ac-layer-on ac-linetype ac-lineweight ac-lock ac-material ac-name ac-object-id ac-object-name ac-owner-id ac-plot-style-name ac-plottable ac-true-color ac-used ac-viewport-default))

(mapcar #'dxf/utils:make-slot (set-difference *acad-layer-properties* *acad-object-properties*))
