(in-package :dxf/classes)

(defclass <acad-lofted-surface> (<acad-entity>)
  (
  (pr-application              :accessor pr-application              :initarg :pr-application              :initform nil :documentation "pr-application")
  (pr-closed                   :accessor pr-closed                   :initarg :pr-closed                   :initform nil :documentation "pr-closed")
  (pr-document                 :accessor pr-document                 :initarg :pr-document                 :initform nil :documentation "pr-document")
  (pr-edge-extension-distances :accessor pr-edge-extension-distances :initarg :pr-edge-extension-distances :initform nil :documentation "pr-edge-extension-distances")
  (pr-end-draft-angle          :accessor pr-end-draft-angle          :initarg :pr-end-draft-angle          :initform nil :documentation "pr-end-draft-angle")
  (pr-end-draft-magnitude      :accessor pr-end-draft-magnitude      :initarg :pr-end-draft-magnitude      :initform nil :documentation "pr-end-draft-magnitude")
  (pr-end-smooth-continuity    :accessor pr-end-smooth-continuity    :initarg :pr-end-smooth-continuity    :initform nil :documentation "pr-end-smooth-continuity")
  (pr-end-smooth-magnitude     :accessor pr-end-smooth-magnitude     :initarg :pr-end-smooth-magnitude     :initform nil :documentation "pr-end-smooth-magnitude")
  (pr-entity-transparency      :accessor pr-entity-transparency      :initarg :pr-entity-transparency      :initform nil :documentation "pr-entity-transparency")
  (pr-handle                   :accessor pr-handle                   :initarg :pr-handle                   :initform nil :documentation "pr-handle")
  (pr-has-extension-dictionary :accessor pr-has-extension-dictionary :initarg :pr-has-extension-dictionary :initform nil :documentation "pr-has-extension-dictionary")
  (pr-hyperlinks               :accessor pr-hyperlinks               :initarg :pr-hyperlinks               :initform nil :documentation "pr-hyperlinks")
  (pr-layer                    :accessor pr-layer                    :initarg :pr-layer                    :initform nil :documentation "pr-layer")
  (pr-linetype                 :accessor pr-linetype                 :initarg :pr-linetype                 :initform nil :documentation "pr-linetype")
  (pr-linetype-scale           :accessor pr-linetype-scale           :initarg :pr-linetype-scale           :initform nil :documentation "pr-linetype-scale")
  (pr-lineweight               :accessor pr-lineweight               :initarg :pr-lineweight               :initform nil :documentation "pr-lineweight")
  (pr-maintain-associativity   :accessor pr-maintain-associativity   :initarg :pr-maintain-associativity   :initform nil :documentation "pr-maintain-associativity")
  (pr-material                 :accessor pr-material                 :initarg :pr-material                 :initform nil :documentation "pr-material")
  (pr-num-cross-sections       :accessor pr-num-cross-sections       :initarg :pr-num-cross-sections       :initform nil :documentation "pr-num-cross-sections")
  (pr-num-guide-paths          :accessor pr-num-guide-paths          :initarg :pr-num-guide-paths          :initform nil :documentation "pr-num-guide-paths")
  (pr-object-id                :accessor pr-object-id                :initarg :pr-object-id                :initform nil :documentation "pr-object-id")
  (pr-object-name              :accessor pr-object-name              :initarg :pr-object-name              :initform nil :documentation "pr-object-name")
  (pr-owner-id                 :accessor pr-owner-id                 :initarg :pr-owner-id                 :initform nil :documentation "pr-owner-id")
  (pr-periodic                 :accessor pr-periodic                 :initarg :pr-periodic                 :initform nil :documentation "pr-periodic")
  (pr-plot-style-name          :accessor pr-plot-style-name          :initarg :pr-plot-style-name          :initform nil :documentation "pr-plot-style-name")
  (pr-show-associativity       :accessor pr-show-associativity       :initarg :pr-show-associativity       :initform nil :documentation "pr-show-associativity")
  (pr-start-draft-angle        :accessor pr-start-draft-angle        :initarg :pr-start-draft-angle        :initform nil :documentation "pr-start-draft-angle")
  (pr-start-draft-magnitude    :accessor pr-start-draft-magnitude    :initarg :pr-start-draft-magnitude    :initform nil :documentation "pr-start-draft-magnitude")
  (pr-start-smooth-continuity  :accessor pr-start-smooth-continuity  :initarg :pr-start-smooth-continuity  :initform nil :documentation "pr-start-smooth-continuity")
  (pr-start-smooth-magnitude   :accessor pr-start-smooth-magnitude   :initarg :pr-start-smooth-magnitude   :initform nil :documentation "pr-start-smooth-magnitude")
  (pr-surface-normals          :accessor pr-surface-normals          :initarg :pr-surface-normals          :initform nil :documentation "pr-surface-normals")
  (pr-surface-type             :accessor pr-surface-type             :initarg :pr-surface-type             :initform nil :documentation "pr-surface-type")
  (pr-surf-trim-associativity  :accessor pr-surf-trim-associativity  :initarg :pr-surf-trim-associativity  :initform nil :documentation "pr-surf-trim-associativity")
  (pr-true-color               :accessor pr-true-color               :initarg :pr-true-color               :initform nil :documentation "pr-true-color")
  (pr-u-isoline-density        :accessor pr-u-isoline-density        :initarg :pr-u-isoline-density        :initform nil :documentation "pr-u-isoline-density")
  (pr-visible                  :accessor pr-visible                  :initarg :pr-visible                  :initform nil :documentation "pr-visible")
  (pr-v-isoline-density        :accessor pr-v-isoline-density        :initarg :pr-v-isoline-density        :initform nil :documentation "pr-v-isoline-density")
  (pr-wireframe-type           :accessor pr-wireframe-type           :initarg :pr-wireframe-type           :initform nil :documentation "pr-wireframe-type")
  )
  (:documentation "
@link[uri=\"https://help.autodesk.com/view/ACD/2022/RUS/?guid=GUID-D56F5C92-731E-4FA3-9FAE-82E97E388901\"](LoftedSurface Object (ActiveX))"))

(defparameter *acad-lofted-surface-properties* '(pr-application pr-closed pr-document pr-edge-extension-distances pr-end-draft-angle pr-end-draft-magnitude pr-end-smooth-continuity pr-end-smooth-magnitude pr-entity-transparency pr-handle pr-has-extension-dictionary pr-hyperlinks pr-layer pr-linetype pr-linetype-scale pr-lineweight pr-maintain-associativity pr-material pr-num-cross-sections pr-num-guide-paths pr-object-id pr-object-name pr-owner-id pr-periodic pr-plot-style-name pr-show-associativity pr-start-draft-angle pr-start-draft-magnitude pr-start-smooth-continuity pr-start-smooth-magnitude pr-surface-normals pr-surface-type pr-surf-trim-associativity pr-true-color pr-u-isoline-density pr-visible pr-v-isoline-density pr-wireframe-type))

(mapcar #'dxf/utils:make-slot (set-difference *acad-lofted-surface-properties* *acad-entity-properties*))
