(in-package :dxf)

(defclass <acad-helix> (<acad-entity>)
  (
  (pr-application              :accessor pr-application              :initarg :pr-application              :initform nil :documentation "pr-application")
  (pr-base-radius              :accessor pr-base-radius              :initarg :pr-base-radius              :initform nil :documentation "pr-base-radius")
  (pr-constrain                :accessor pr-constrain                :initarg :pr-constrain                :initform nil :documentation "pr-constrain")
  (pr-document                 :accessor pr-document                 :initarg :pr-document                 :initform nil :documentation "pr-document")
  (pr-entity-transparency      :accessor pr-entity-transparency      :initarg :pr-entity-transparency      :initform nil :documentation "pr-entity-transparency")
  (pr-handle                   :accessor pr-handle                   :initarg :pr-handle                   :initform nil :documentation "pr-handle")
  (pr-has-extension-dictionary :accessor pr-has-extension-dictionary :initarg :pr-has-extension-dictionary :initform nil :documentation "pr-has-extension-dictionary")
  (pr-height                   :accessor pr-height                   :initarg :pr-height                   :initform nil :documentation "pr-height")
  (pr-hyperlinks               :accessor pr-hyperlinks               :initarg :pr-hyperlinks               :initform nil :documentation "pr-hyperlinks")
  (pr-layer                    :accessor pr-layer                    :initarg :pr-layer                    :initform nil :documentation "pr-layer")
  (pr-linetype                 :accessor pr-linetype                 :initarg :pr-linetype                 :initform nil :documentation "pr-linetype")
  (pr-linetype-scale           :accessor pr-linetype-scale           :initarg :pr-linetype-scale           :initform nil :documentation "pr-linetype-scale")
  (pr-lineweight               :accessor pr-lineweight               :initarg :pr-lineweight               :initform nil :documentation "pr-lineweight")
  (pr-material                 :accessor pr-material                 :initarg :pr-material                 :initform nil :documentation "pr-material")
  (pr-object-id                :accessor pr-object-id                :initarg :pr-object-id                :initform nil :documentation "pr-object-id")
  (pr-object-name              :accessor pr-object-name              :initarg :pr-object-name              :initform nil :documentation "pr-object-name")
  (pr-owner-id                 :accessor pr-owner-id                 :initarg :pr-owner-id                 :initform nil :documentation "pr-owner-id")
  (pr-plot-style-name          :accessor pr-plot-style-name          :initarg :pr-plot-style-name          :initform nil :documentation "pr-plot-style-name")
  (pr-position                 :accessor pr-position                 :initarg :pr-position                 :initform nil :documentation "pr-position")
  (pr-top-radius               :accessor pr-top-radius               :initarg :pr-top-radius               :initform nil :documentation "pr-top-radius")
  (pr-total-length             :accessor pr-total-length             :initarg :pr-total-length             :initform nil :documentation "pr-total-length")
  (pr-true-color               :accessor pr-true-color               :initarg :pr-true-color               :initform nil :documentation "pr-true-color")
  (pr-turn-height              :accessor pr-turn-height              :initarg :pr-turn-height              :initform nil :documentation "pr-turn-height")
  (pr-turns                    :accessor pr-turns                    :initarg :pr-turns                    :initform nil :documentation "pr-turns")
  (pr-turn-slope               :accessor pr-turn-slope               :initarg :pr-turn-slope               :initform nil :documentation "pr-turn-slope")
  (pr-twist                    :accessor pr-twist                    :initarg :pr-twist                    :initform nil :documentation "pr-twist")
  (pr-visible                  :accessor pr-visible                  :initarg :pr-visible                  :initform nil :documentation "pr-visible")
  )
  (:documentation "
@link[uri=\"https://help.autodesk.com/view/ACD/2022/RUS/?guid=GUID-A8B144D8-EFC1-4D2D-B6F8-73C541906646\"](Helix Object (ActiveX))"))

(defparameter *acad-helix-properties* '(pr-application pr-base-radius pr-constrain pr-document pr-entity-transparency pr-handle pr-has-extension-dictionary pr-height pr-hyperlinks pr-layer pr-linetype pr-linetype-scale pr-lineweight pr-material pr-object-id pr-object-name pr-owner-id pr-plot-style-name pr-position pr-top-radius pr-total-length pr-true-color pr-turn-height pr-turns pr-turn-slope pr-twist pr-visible))

(mapcar #'dxf/utils:make-slot (set-difference *acad-helix-properties* *acad-entity-properties*))
