(in-package :dxf/classes)

(defclass <acad-dim-3point-angular> (<acad-dimension>)
  (
  (pr-angle-format             :accessor pr-angle-format             :initarg :pr-angle-format             :initform nil :documentation "pr-angle-format")
  (pr-angle-vertex             :accessor pr-angle-vertex             :initarg :pr-angle-vertex             :initform nil :documentation "pr-angle-vertex")
  (pr-application              :accessor pr-application              :initarg :pr-application              :initform nil :documentation "pr-application")
  (pr-arrowhead1-block         :accessor pr-arrowhead1-block         :initarg :pr-arrowhead1-block         :initform nil :documentation "pr-arrowhead1-block")
  (pr-arrowhead1-type          :accessor pr-arrowhead1-type          :initarg :pr-arrowhead1-type          :initform nil :documentation "pr-arrowhead1-type")
  (pr-arrowhead2-block         :accessor pr-arrowhead2-block         :initarg :pr-arrowhead2-block         :initform nil :documentation "pr-arrowhead2-block")
  (pr-arrowhead2-type          :accessor pr-arrowhead2-type          :initarg :pr-arrowhead2-type          :initform nil :documentation "pr-arrowhead2-type")
  (pr-arrowhead-size           :accessor pr-arrowhead-size           :initarg :pr-arrowhead-size           :initform nil :documentation "pr-arrowhead-size")
  (pr-decimal-separator        :accessor pr-decimal-separator        :initarg :pr-decimal-separator        :initform nil :documentation "pr-decimal-separator")
  (pr-dim-constr-desc          :accessor pr-dim-constr-desc          :initarg :pr-dim-constr-desc          :initform nil :documentation "pr-dim-constr-desc")
  (pr-dim-constr-expression    :accessor pr-dim-constr-expression    :initarg :pr-dim-constr-expression    :initform nil :documentation "pr-dim-constr-expression")
  (pr-dim-constr-form          :accessor pr-dim-constr-form          :initarg :pr-dim-constr-form          :initform nil :documentation "pr-dim-constr-form")
  (pr-dim-constr-name          :accessor pr-dim-constr-name          :initarg :pr-dim-constr-name          :initform nil :documentation "pr-dim-constr-name")
  (pr-dim-constr-reference     :accessor pr-dim-constr-reference     :initarg :pr-dim-constr-reference     :initform nil :documentation "pr-dim-constr-reference")
  (pr-dim-constr-value         :accessor pr-dim-constr-value         :initarg :pr-dim-constr-value         :initform nil :documentation "pr-dim-constr-value")
  (pr-dimension-line-color     :accessor pr-dimension-line-color     :initarg :pr-dimension-line-color     :initform nil :documentation "pr-dimension-line-color")
  (pr-dimension-linetype       :accessor pr-dimension-linetype       :initarg :pr-dimension-linetype       :initform nil :documentation "pr-dimension-linetype")
  (pr-dimension-line-weight    :accessor pr-dimension-line-weight    :initarg :pr-dimension-line-weight    :initform nil :documentation "pr-dimension-line-weight")
  (pr-dim-line1-suppress       :accessor pr-dim-line1-suppress       :initarg :pr-dim-line1-suppress       :initform nil :documentation "pr-dim-line1-suppress")
  (pr-dim-line2-suppress       :accessor pr-dim-line2-suppress       :initarg :pr-dim-line2-suppress       :initform nil :documentation "pr-dim-line2-suppress")
  (pr-dim-line-inside          :accessor pr-dim-line-inside          :initarg :pr-dim-line-inside          :initform nil :documentation "pr-dim-line-inside")
  (pr-dim-txt-direction        :accessor pr-dim-txt-direction        :initarg :pr-dim-txt-direction        :initform nil :documentation "pr-dim-txt-direction")
  (pr-document                 :accessor pr-document                 :initarg :pr-document                 :initform nil :documentation "pr-document")
  (pr-entity-transparency      :accessor pr-entity-transparency      :initarg :pr-entity-transparency      :initform nil :documentation "pr-entity-transparency")
  (pr-extension-line-color     :accessor pr-extension-line-color     :initarg :pr-extension-line-color     :initform nil :documentation "pr-extension-line-color")
  (pr-extension-line-extend    :accessor pr-extension-line-extend    :initarg :pr-extension-line-extend    :initform nil :documentation "pr-extension-line-extend")
  (pr-extension-line-offset    :accessor pr-extension-line-offset    :initarg :pr-extension-line-offset    :initform nil :documentation "pr-extension-line-offset")
  (pr-extension-line-weight    :accessor pr-extension-line-weight    :initarg :pr-extension-line-weight    :initform nil :documentation "pr-extension-line-weight")
  (pr-ext-line1-end-point      :accessor pr-ext-line1-end-point      :initarg :pr-ext-line1-end-point      :initform nil :documentation "pr-ext-line1-end-point")
  (pr-ext-line1-linetype       :accessor pr-ext-line1-linetype       :initarg :pr-ext-line1-linetype       :initform nil :documentation "pr-ext-line1-linetype")
  (pr-ext-line1-suppress       :accessor pr-ext-line1-suppress       :initarg :pr-ext-line1-suppress       :initform nil :documentation "pr-ext-line1-suppress")
  (pr-ext-line2-end-point      :accessor pr-ext-line2-end-point      :initarg :pr-ext-line2-end-point      :initform nil :documentation "pr-ext-line2-end-point")
  (pr-ext-line2-linetype       :accessor pr-ext-line2-linetype       :initarg :pr-ext-line2-linetype       :initform nil :documentation "pr-ext-line2-linetype")
  (pr-ext-line2-suppress       :accessor pr-ext-line2-suppress       :initarg :pr-ext-line2-suppress       :initform nil :documentation "pr-ext-line2-suppress")
  (pr-ext-line-fixed-len       :accessor pr-ext-line-fixed-len       :initarg :pr-ext-line-fixed-len       :initform nil :documentation "pr-ext-line-fixed-len")
  (pr-ext-line-fixed-len-suppress :accessor pr-ext-line-fixed-len-suppress :initarg :pr-ext-line-fixed-len-suppress :initform nil :documentation "pr-ext-line-fixed-len-suppress")
  (pr-fit                      :accessor pr-fit                      :initarg :pr-fit                      :initform nil :documentation "pr-fit")
  (pr-force-line-inside        :accessor pr-force-line-inside        :initarg :pr-force-line-inside        :initform nil :documentation "pr-force-line-inside")
  (pr-handle                   :accessor pr-handle                   :initarg :pr-handle                   :initform nil :documentation "pr-handle")
  (pr-has-extension-dictionary :accessor pr-has-extension-dictionary :initarg :pr-has-extension-dictionary :initform nil :documentation "pr-has-extension-dictionary")
  (pr-horizontal-text-position :accessor pr-horizontal-text-position :initarg :pr-horizontal-text-position :initform nil :documentation "pr-horizontal-text-position")
  (pr-hyperlinks               :accessor pr-hyperlinks               :initarg :pr-hyperlinks               :initform nil :documentation "pr-hyperlinks")
  (pr-layer                    :accessor pr-layer                    :initarg :pr-layer                    :initform nil :documentation "pr-layer")
  (pr-linetype                 :accessor pr-linetype                 :initarg :pr-linetype                 :initform nil :documentation "pr-linetype")
  (pr-linetype-scale           :accessor pr-linetype-scale           :initarg :pr-linetype-scale           :initform nil :documentation "pr-linetype-scale")
  (pr-lineweight               :accessor pr-lineweight               :initarg :pr-lineweight               :initform nil :documentation "pr-lineweight")
  (pr-material                 :accessor pr-material                 :initarg :pr-material                 :initform nil :documentation "pr-material")
  (pr-measurement              :accessor pr-measurement              :initarg :pr-measurement              :initform nil :documentation "pr-measurement")
  (pr-normal                   :accessor pr-normal                   :initarg :pr-normal                   :initform nil :documentation "pr-normal")
  (pr-object-id                :accessor pr-object-id                :initarg :pr-object-id                :initform nil :documentation "pr-object-id")
  (pr-object-name              :accessor pr-object-name              :initarg :pr-object-name              :initform nil :documentation "pr-object-name")
  (pr-owner-id                 :accessor pr-owner-id                 :initarg :pr-owner-id                 :initform nil :documentation "pr-owner-id")
  (pr-plot-style-name          :accessor pr-plot-style-name          :initarg :pr-plot-style-name          :initform nil :documentation "pr-plot-style-name")
  (pr-rotation                 :accessor pr-rotation                 :initarg :pr-rotation                 :initform nil :documentation "pr-rotation")
  (pr-scale-factor             :accessor pr-scale-factor             :initarg :pr-scale-factor             :initform nil :documentation "pr-scale-factor")
  (pr-style-name               :accessor pr-style-name               :initarg :pr-style-name               :initform nil :documentation "pr-style-name")
  (pr-suppress-leading-zeros   :accessor pr-suppress-leading-zeros   :initarg :pr-suppress-leading-zeros   :initform nil :documentation "pr-suppress-leading-zeros")
  (pr-suppress-trailing-zeros  :accessor pr-suppress-trailing-zeros  :initarg :pr-suppress-trailing-zeros  :initform nil :documentation "pr-suppress-trailing-zeros")
  (pr-text-color               :accessor pr-text-color               :initarg :pr-text-color               :initform nil :documentation "pr-text-color")
  (pr-text-fill                :accessor pr-text-fill                :initarg :pr-text-fill                :initform nil :documentation "pr-text-fill")
  (pr-text-fill-color          :accessor pr-text-fill-color          :initarg :pr-text-fill-color          :initform nil :documentation "pr-text-fill-color")
  (pr-text-gap                 :accessor pr-text-gap                 :initarg :pr-text-gap                 :initform nil :documentation "pr-text-gap")
  (pr-text-height              :accessor pr-text-height              :initarg :pr-text-height              :initform nil :documentation "pr-text-height")
  (pr-text-inside              :accessor pr-text-inside              :initarg :pr-text-inside              :initform nil :documentation "pr-text-inside")
  (pr-text-inside-align        :accessor pr-text-inside-align        :initarg :pr-text-inside-align        :initform nil :documentation "pr-text-inside-align")
  (pr-text-movement            :accessor pr-text-movement            :initarg :pr-text-movement            :initform nil :documentation "pr-text-movement")
  (pr-text-outside-align       :accessor pr-text-outside-align       :initarg :pr-text-outside-align       :initform nil :documentation "pr-text-outside-align")
  (pr-text-override            :accessor pr-text-override            :initarg :pr-text-override            :initform nil :documentation "pr-text-override")
  (pr-text-position            :accessor pr-text-position            :initarg :pr-text-position            :initform nil :documentation "pr-text-position")
  (pr-text-precision           :accessor pr-text-precision           :initarg :pr-text-precision           :initform nil :documentation "pr-text-precision")
  (pr-text-prefix              :accessor pr-text-prefix              :initarg :pr-text-prefix              :initform nil :documentation "pr-text-prefix")
  (pr-text-rotation            :accessor pr-text-rotation            :initarg :pr-text-rotation            :initform nil :documentation "pr-text-rotation")
  (pr-text-style               :accessor pr-text-style               :initarg :pr-text-style               :initform nil :documentation "pr-text-style")
  (pr-text-suffix              :accessor pr-text-suffix              :initarg :pr-text-suffix              :initform nil :documentation "pr-text-suffix")
  (pr-tolerance-display        :accessor pr-tolerance-display        :initarg :pr-tolerance-display        :initform nil :documentation "pr-tolerance-display")
  (pr-tolerance-height-scale   :accessor pr-tolerance-height-scale   :initarg :pr-tolerance-height-scale   :initform nil :documentation "pr-tolerance-height-scale")
  (pr-tolerance-justification  :accessor pr-tolerance-justification  :initarg :pr-tolerance-justification  :initform nil :documentation "pr-tolerance-justification")
  (pr-tolerance-lower-limit    :accessor pr-tolerance-lower-limit    :initarg :pr-tolerance-lower-limit    :initform nil :documentation "pr-tolerance-lower-limit")
  (pr-tolerance-precision      :accessor pr-tolerance-precision      :initarg :pr-tolerance-precision      :initform nil :documentation "pr-tolerance-precision")
  (pr-tolerance-suppress-leading-zeros :accessor pr-tolerance-suppress-leading-zeros :initarg :pr-tolerance-suppress-leading-zeros :initform nil :documentation "pr-tolerance-suppress-leading-zeros")
  (pr-tolerance-suppress-trailing-zeros :accessor pr-tolerance-suppress-trailing-zeros :initarg :pr-tolerance-suppress-trailing-zeros :initform nil :documentation "pr-tolerance-suppress-trailing-zeros")
  (pr-tolerance-upper-limit    :accessor pr-tolerance-upper-limit    :initarg :pr-tolerance-upper-limit    :initform nil :documentation "pr-tolerance-upper-limit")
  (pr-true-color               :accessor pr-true-color               :initarg :pr-true-color               :initform nil :documentation "pr-true-color")
  (pr-vertical-text-position   :accessor pr-vertical-text-position   :initarg :pr-vertical-text-position   :initform nil :documentation "pr-vertical-text-position")
  (pr-visible                  :accessor pr-visible                  :initarg :pr-visible                  :initform nil :documentation "pr-visible")
  )
  (:documentation "
@link[uri=\"https://help.autodesk.com/view/ACD/2022/RUS/?guid=GUID-1EF38BC6-8057-4F4A-95BC-0624544A248F\"](Dim3PointAngular Object (ActiveX))"))

(defparameter *acad-dim3-point-angular-properties* '(pr-angle-format pr-angle-vertex pr-application pr-arrowhead1-block pr-arrowhead1-type pr-arrowhead2-block pr-arrowhead2-type pr-arrowhead-size pr-decimal-separator pr-dim-constr-desc pr-dim-constr-expression pr-dim-constr-form pr-dim-constr-name pr-dim-constr-reference pr-dim-constr-value pr-dimension-line-color pr-dimension-linetype pr-dimension-line-weight pr-dim-line1-suppress pr-dim-line2-suppress pr-dim-line-inside pr-dim-txt-direction pr-document pr-entity-transparency pr-extension-line-color pr-extension-line-extend pr-extension-line-offset pr-extension-line-weight pr-ext-line1-end-point pr-ext-line1-linetype pr-ext-line1-suppress pr-ext-line2-end-point pr-ext-line2-linetype pr-ext-line2-suppress pr-ext-line-fixed-len pr-ext-line-fixed-len-suppress pr-fit pr-force-line-inside pr-handle pr-has-extension-dictionary pr-horizontal-text-position pr-hyperlinks pr-layer pr-linetype pr-linetype-scale pr-lineweight pr-material pr-measurement pr-normal pr-object-id pr-object-name pr-owner-id pr-plot-style-name pr-rotation pr-scale-factor pr-style-name pr-suppress-leading-zeros pr-suppress-trailing-zeros pr-text-color pr-text-fill pr-text-fill-color pr-text-gap pr-text-height pr-text-inside pr-text-inside-align pr-text-movement pr-text-outside-align pr-text-override pr-text-position pr-text-precision pr-text-prefix pr-text-rotation pr-text-style pr-text-suffix pr-tolerance-display pr-tolerance-height-scale pr-tolerance-justification pr-tolerance-lower-limit pr-tolerance-precision pr-tolerance-suppress-leading-zeros pr-tolerance-suppress-trailing-zeros pr-tolerance-upper-limit pr-true-color pr-vertical-text-position pr-visible))

(mapcar #'dxf/utils:make-slot (set-difference *acad-dim3-point-angular-properties* *acad-dimension-properties*))
