(defclass acad-document (acad-database)
  (
  (ac-active                   :accessor ac-active                   :initarg :ac-active                   :initform nil :documentation "ac-active")
  (ac-active-dim-style         :accessor ac-active-dim-style         :initarg :ac-active-dim-style         :initform nil :documentation "ac-active-dim-style")
  (ac-active-layer             :accessor ac-active-layer             :initarg :ac-active-layer             :initform nil :documentation "ac-active-layer")
  (ac-active-layout            :accessor ac-active-layout            :initarg :ac-active-layout            :initform nil :documentation "ac-active-layout")
  (ac-active-linetype          :accessor ac-active-linetype          :initarg :ac-active-linetype          :initform nil :documentation "ac-active-linetype")
  (ac-active-material          :accessor ac-active-material          :initarg :ac-active-material          :initform nil :documentation "ac-active-material")
  (ac-active-p-viewport        :accessor ac-active-p-viewport        :initarg :ac-active-p-viewport        :initform nil :documentation "ac-active-p-viewport")
  (ac-active-selection-set     :accessor ac-active-selection-set     :initarg :ac-active-selection-set     :initform nil :documentation "ac-active-selection-set")
  (ac-active-space             :accessor ac-active-space             :initarg :ac-active-space             :initform nil :documentation "ac-active-space")
  (ac-active-text-style        :accessor ac-active-text-style        :initarg :ac-active-text-style        :initform nil :documentation "ac-active-text-style")
  (ac-active-ucs               :accessor ac-active-ucs               :initarg :ac-active-ucs               :initform nil :documentation "ac-active-ucs")
  (ac-active-viewport          :accessor ac-active-viewport          :initarg :ac-active-viewport          :initform nil :documentation "ac-active-viewport")
  (ac-application              :accessor ac-application              :initarg :ac-application              :initform nil :documentation "ac-application")
  (ac-blocks                   :accessor ac-blocks                   :initarg :ac-blocks                   :initform nil :documentation "ac-blocks")
  (ac-database                 :accessor ac-database                 :initarg :ac-database                 :initform nil :documentation "ac-database")
  (ac-dictionaries             :accessor ac-dictionaries             :initarg :ac-dictionaries             :initform nil :documentation "ac-dictionaries")
  (ac-dim-styles               :accessor ac-dim-styles               :initarg :ac-dim-styles               :initform nil :documentation "ac-dim-styles")
  (ac-elevation-model-space    :accessor ac-elevation-model-space    :initarg :ac-elevation-model-space    :initform nil :documentation "ac-elevation-model-space")
  (ac-elevation-paper-space    :accessor ac-elevation-paper-space    :initarg :ac-elevation-paper-space    :initform nil :documentation "ac-elevation-paper-space")
  (ac-full-name                :accessor ac-full-name                :initarg :ac-full-name                :initform nil :documentation "ac-full-name")
  (ac-groups                   :accessor ac-groups                   :initarg :ac-groups                   :initform nil :documentation "ac-groups")
  (ac-height                   :accessor ac-height                   :initarg :ac-height                   :initform nil :documentation "ac-height")
  (ac-hwnd                     :accessor ac-hwnd                     :initarg :ac-hwnd                     :initform nil :documentation "ac-hwnd")
  (ac-layers                   :accessor ac-layers                   :initarg :ac-layers                   :initform nil :documentation "ac-layers")
  (ac-layouts                  :accessor ac-layouts                  :initarg :ac-layouts                  :initform nil :documentation "ac-layouts")
  (ac-limits                   :accessor ac-limits                   :initarg :ac-limits                   :initform nil :documentation "ac-limits")
  (ac-linetypes                :accessor ac-linetypes                :initarg :ac-linetypes                :initform nil :documentation "ac-linetypes")
  (ac-materials                :accessor ac-materials                :initarg :ac-materials                :initform nil :documentation "ac-materials")
  (ac-model-space              :accessor ac-model-space              :initarg :ac-model-space              :initform nil :documentation "ac-model-space")
  (ac-m-space                  :accessor ac-m-space                  :initarg :ac-m-space                  :initform nil :documentation "ac-m-space")
  (ac-name                     :accessor ac-name                     :initarg :ac-name                     :initform nil :documentation "ac-name")
  (ac-object-snap-mode         :accessor ac-object-snap-mode         :initarg :ac-object-snap-mode         :initform nil :documentation "ac-object-snap-mode")
  (ac-paper-space              :accessor ac-paper-space              :initarg :ac-paper-space              :initform nil :documentation "ac-paper-space")
  (ac-path                     :accessor ac-path                     :initarg :ac-path                     :initform nil :documentation "ac-path")
  (ac-pickfirst-selection-set  :accessor ac-pickfirst-selection-set  :initarg :ac-pickfirst-selection-set  :initform nil :documentation "ac-pickfirst-selection-set")
  (ac-plot                     :accessor ac-plot                     :initarg :ac-plot                     :initform nil :documentation "ac-plot")
  (ac-plot-configurations      :accessor ac-plot-configurations      :initarg :ac-plot-configurations      :initform nil :documentation "ac-plot-configurations")
  (ac-preferences              :accessor ac-preferences              :initarg :ac-preferences              :initform nil :documentation "ac-preferences")
  (ac-read-only                :accessor ac-read-only                :initarg :ac-read-only                :initform nil :documentation "ac-read-only")
  (ac-registered-applications  :accessor ac-registered-applications  :initarg :ac-registered-applications  :initform nil :documentation "ac-registered-applications")
  (ac-saved                    :accessor ac-saved                    :initarg :ac-saved                    :initform nil :documentation "ac-saved")
  (ac-section-manager          :accessor ac-section-manager          :initarg :ac-section-manager          :initform nil :documentation "ac-section-manager")
  (ac-selection-sets           :accessor ac-selection-sets           :initarg :ac-selection-sets           :initform nil :documentation "ac-selection-sets")
  (ac-summary-info             :accessor ac-summary-info             :initarg :ac-summary-info             :initform nil :documentation "ac-summary-info")
  (ac-text-styles              :accessor ac-text-styles              :initarg :ac-text-styles              :initform nil :documentation "ac-text-styles")
  (ac-user-coordinate-systems  :accessor ac-user-coordinate-systems  :initarg :ac-user-coordinate-systems  :initform nil :documentation "ac-user-coordinate-systems")
  (ac-utility                  :accessor ac-utility                  :initarg :ac-utility                  :initform nil :documentation "ac-utility")
  (ac-viewports                :accessor ac-viewports                :initarg :ac-viewports                :initform nil :documentation "ac-viewports")
  (ac-views                    :accessor ac-views                    :initarg :ac-views                    :initform nil :documentation "ac-views")
  (ac-width                    :accessor ac-width                    :initarg :ac-width                    :initform nil :documentation "ac-width")
  (ac-window-state             :accessor ac-window-state             :initarg :ac-window-state             :initform nil :documentation "ac-window-state")
  (ac-window-title             :accessor ac-window-title             :initarg :ac-window-title             :initform nil :documentation "ac-window-title")
  )
  (:documentation "An AutoCAD drawing."))

(defparameter *acad-document-properties* '(ac-active ac-active-dim-style ac-active-layer ac-active-layout ac-active-linetype ac-active-material ac-active-p-viewport ac-active-selection-set ac-active-space ac-active-text-style ac-active-ucs ac-active-viewport ac-application ac-blocks ac-database ac-dictionaries ac-dim-styles ac-elevation-model-space ac-elevation-paper-space ac-full-name ac-groups ac-height ac-hwnd ac-layers ac-layouts ac-limits ac-linetypes ac-materials ac-model-space ac-m-space ac-name ac-object-snap-mode ac-paper-space ac-path ac-pickfirst-selection-set ac-plot ac-plot-configurations ac-preferences ac-read-only ac-registered-applications ac-saved ac-section-manager ac-selection-sets ac-summary-info ac-text-styles ac-user-coordinate-systems ac-utility ac-viewports ac-views ac-width ac-window-state ac-window-title))

(mapcar #'make-slot (set-difference *acad-document-properties* *acad-database-properties*))