(defclass acad-geo-position-marker (acad-entity)
  (
  (ac-altitude                 :accessor ac-altitude                 :initarg :ac-altitude                 :initform nil :documentation "ac-altitude")
  (ac-application              :accessor ac-application              :initarg :ac-application              :initform nil :documentation "ac-application")
  (ac-background-fill          :accessor ac-background-fill          :initarg :ac-background-fill          :initform nil :documentation "ac-background-fill")
  (ac-document                 :accessor ac-document                 :initarg :ac-document                 :initform nil :documentation "ac-document")
  (ac-drawing-direction        :accessor ac-drawing-direction        :initarg :ac-drawing-direction        :initform nil :documentation "ac-drawing-direction")
  (ac-entity-transparency      :accessor ac-entity-transparency      :initarg :ac-entity-transparency      :initform nil :documentation "ac-entity-transparency")
  (ac-handle                   :accessor ac-handle                   :initarg :ac-handle                   :initform nil :documentation "ac-handle")
  (ac-has-extension-dictionary :accessor ac-has-extension-dictionary :initarg :ac-has-extension-dictionary :initform nil :documentation "ac-has-extension-dictionary")
  (ac-height                   :accessor ac-height                   :initarg :ac-height                   :initform nil :documentation "ac-height")
  (ac-landing-gap              :accessor ac-landing-gap              :initarg :ac-landing-gap              :initform nil :documentation "ac-landing-gap")
  (ac-latitude                 :accessor ac-latitude                 :initarg :ac-latitude                 :initform nil :documentation "ac-latitude")
  (ac-layer                    :accessor ac-layer                    :initarg :ac-layer                    :initform nil :documentation "ac-layer")
  (ac-line-spacing-distance    :accessor ac-line-spacing-distance    :initarg :ac-line-spacing-distance    :initform nil :documentation "ac-line-spacing-distance")
  (ac-line-spacing-factor      :accessor ac-line-spacing-factor      :initarg :ac-line-spacing-factor      :initform nil :documentation "ac-line-spacing-factor")
  (ac-line-spacing-style       :accessor ac-line-spacing-style       :initarg :ac-line-spacing-style       :initform nil :documentation "ac-line-spacing-style")
  (ac-linetype                 :accessor ac-linetype                 :initarg :ac-linetype                 :initform nil :documentation "ac-linetype")
  (ac-linetype-scale           :accessor ac-linetype-scale           :initarg :ac-linetype-scale           :initform nil :documentation "ac-linetype-scale")
  (ac-lineweight               :accessor ac-lineweight               :initarg :ac-lineweight               :initform nil :documentation "ac-lineweight")
  (ac-longitude                :accessor ac-longitude                :initarg :ac-longitude                :initform nil :documentation "ac-longitude")
  (ac-material                 :accessor ac-material                 :initarg :ac-material                 :initform nil :documentation "ac-material")
  (ac-notes                    :accessor ac-notes                    :initarg :ac-notes                    :initform nil :documentation "ac-notes")
  (ac-object-id                :accessor ac-object-id                :initarg :ac-object-id                :initform nil :documentation "ac-object-id")
  (ac-object-name              :accessor ac-object-name              :initarg :ac-object-name              :initform nil :documentation "ac-object-name")
  (ac-owner-id                 :accessor ac-owner-id                 :initarg :ac-owner-id                 :initform nil :documentation "ac-owner-id")
  (ac-plot-style-name          :accessor ac-plot-style-name          :initarg :ac-plot-style-name          :initform nil :documentation "ac-plot-style-name")
  (ac-position                 :accessor ac-position                 :initarg :ac-position                 :initform nil :documentation "ac-position")
  (ac-radius                   :accessor ac-radius                   :initarg :ac-radius                   :initform nil :documentation "ac-radius")
  (ac-rotation                 :accessor ac-rotation                 :initarg :ac-rotation                 :initform nil :documentation "ac-rotation")
  (ac-text-frame-display       :accessor ac-text-frame-display       :initarg :ac-text-frame-display       :initform nil :documentation "ac-text-frame-display")
  (ac-text-justify             :accessor ac-text-justify             :initarg :ac-text-justify             :initform nil :documentation "ac-text-justify")
  (ac-text-string              :accessor ac-text-string              :initarg :ac-text-string              :initform nil :documentation "ac-text-string")
  (ac-text-style-name          :accessor ac-text-style-name          :initarg :ac-text-style-name          :initform nil :documentation "ac-text-style-name")
  (ac-text-width               :accessor ac-text-width               :initarg :ac-text-width               :initform nil :documentation "ac-text-width")
  (ac-true-color               :accessor ac-true-color               :initarg :ac-true-color               :initform nil :documentation "ac-true-color")
  (ac-visible                  :accessor ac-visible                  :initarg :ac-visible                  :initform nil :documentation "ac-visible")
  )
  (:documentation "A geographical location aware marker object with a label."))

(defparameter *acad-geo-position-marker-properties* '(ac-altitude ac-application ac-background-fill ac-document ac-drawing-direction ac-entity-transparency ac-handle ac-has-extension-dictionary ac-height ac-landing-gap ac-latitude ac-layer ac-line-spacing-distance ac-line-spacing-factor ac-line-spacing-style ac-linetype ac-linetype-scale ac-lineweight ac-longitude ac-material ac-notes ac-object-id ac-object-name ac-owner-id ac-plot-style-name ac-position ac-radius ac-rotation ac-text-frame-display ac-text-justify ac-text-string ac-text-style-name ac-text-width ac-true-color ac-visible))

(mapcar #'make-slot (set-difference *acad-geo-position-marker-properties* *acad-entity-properties*))