(defclass acad-spline (acad-entity)
  (
  (ac-application              :accessor ac-application              :initarg :ac-application              :initform nil :documentation "ac-application")
  (ac-area                     :accessor ac-area                     :initarg :ac-area                     :initform nil :documentation "ac-area")
  (ac-closed                   :accessor ac-closed                   :initarg :ac-closed                   :initform nil :documentation "ac-closed")
  (ac-closed2                  :accessor ac-closed2                  :initarg :ac-closed2                  :initform nil :documentation "ac-closed2")
  (ac-control-points           :accessor ac-control-points           :initarg :ac-control-points           :initform nil :documentation "ac-control-points")
  (ac-degree                   :accessor ac-degree                   :initarg :ac-degree                   :initform nil :documentation "ac-degree")
  (ac-degree2                  :accessor ac-degree2                  :initarg :ac-degree2                  :initform nil :documentation "ac-degree2")
  (ac-document                 :accessor ac-document                 :initarg :ac-document                 :initform nil :documentation "ac-document")
  (ac-end-tangent              :accessor ac-end-tangent              :initarg :ac-end-tangent              :initform nil :documentation "ac-end-tangent")
  (ac-entity-transparency      :accessor ac-entity-transparency      :initarg :ac-entity-transparency      :initform nil :documentation "ac-entity-transparency")
  (ac-fit-points               :accessor ac-fit-points               :initarg :ac-fit-points               :initform nil :documentation "ac-fit-points")
  (ac-fit-tolerance            :accessor ac-fit-tolerance            :initarg :ac-fit-tolerance            :initform nil :documentation "ac-fit-tolerance")
  (ac-handle                   :accessor ac-handle                   :initarg :ac-handle                   :initform nil :documentation "ac-handle")
  (ac-has-extension-dictionary :accessor ac-has-extension-dictionary :initarg :ac-has-extension-dictionary :initform nil :documentation "ac-has-extension-dictionary")
  (ac-hyperlinks               :accessor ac-hyperlinks               :initarg :ac-hyperlinks               :initform nil :documentation "ac-hyperlinks")
  (ac-is-periodic              :accessor ac-is-periodic              :initarg :ac-is-periodic              :initform nil :documentation "ac-is-periodic")
  (ac-is-planar                :accessor ac-is-planar                :initarg :ac-is-planar                :initform nil :documentation "ac-is-planar")
  (ac-is-rational              :accessor ac-is-rational              :initarg :ac-is-rational              :initform nil :documentation "ac-is-rational")
  (ac-knot-parameterization    :accessor ac-knot-parameterization    :initarg :ac-knot-parameterization    :initform nil :documentation "ac-knot-parameterization")
  (ac-knots                    :accessor ac-knots                    :initarg :ac-knots                    :initform nil :documentation "ac-knots")
  (ac-layer                    :accessor ac-layer                    :initarg :ac-layer                    :initform nil :documentation "ac-layer")
  (ac-linetype                 :accessor ac-linetype                 :initarg :ac-linetype                 :initform nil :documentation "ac-linetype")
  (ac-linetype-scale           :accessor ac-linetype-scale           :initarg :ac-linetype-scale           :initform nil :documentation "ac-linetype-scale")
  (ac-lineweight               :accessor ac-lineweight               :initarg :ac-lineweight               :initform nil :documentation "ac-lineweight")
  (ac-material                 :accessor ac-material                 :initarg :ac-material                 :initform nil :documentation "ac-material")
  (ac-number-of-control-points :accessor ac-number-of-control-points :initarg :ac-number-of-control-points :initform nil :documentation "ac-number-of-control-points")
  (ac-number-of-fit-points     :accessor ac-number-of-fit-points     :initarg :ac-number-of-fit-points     :initform nil :documentation "ac-number-of-fit-points")
  (ac-object-id                :accessor ac-object-id                :initarg :ac-object-id                :initform nil :documentation "ac-object-id")
  (ac-object-name              :accessor ac-object-name              :initarg :ac-object-name              :initform nil :documentation "ac-object-name")
  (ac-owner-id                 :accessor ac-owner-id                 :initarg :ac-owner-id                 :initform nil :documentation "ac-owner-id")
  (ac-plot-style-name          :accessor ac-plot-style-name          :initarg :ac-plot-style-name          :initform nil :documentation "ac-plot-style-name")
  (ac-spline-frame             :accessor ac-spline-frame             :initarg :ac-spline-frame             :initform nil :documentation "ac-spline-frame")
  (ac-spline-method            :accessor ac-spline-method            :initarg :ac-spline-method            :initform nil :documentation "ac-spline-method")
  (ac-start-tangent            :accessor ac-start-tangent            :initarg :ac-start-tangent            :initform nil :documentation "ac-start-tangent")
  (ac-true-color               :accessor ac-true-color               :initarg :ac-true-color               :initform nil :documentation "ac-true-color")
  (ac-visible                  :accessor ac-visible                  :initarg :ac-visible                  :initform nil :documentation "ac-visible")
  (ac-weights                  :accessor ac-weights                  :initarg :ac-weights                  :initform nil :documentation "ac-weights")
  )
  (:documentation "A quadratic or cubic NURBS (nonuniform rational B-spline) curve."))

(defparameter *acad-spline-properties* '(ac-application ac-area ac-closed ac-closed2 ac-control-points ac-degree ac-degree2 ac-document ac-end-tangent ac-entity-transparency ac-fit-points ac-fit-tolerance ac-handle ac-has-extension-dictionary ac-hyperlinks ac-is-periodic ac-is-planar ac-is-rational ac-knot-parameterization ac-knots ac-layer ac-linetype ac-linetype-scale ac-lineweight ac-material ac-number-of-control-points ac-number-of-fit-points ac-object-id ac-object-name ac-owner-id ac-plot-style-name ac-spline-frame ac-spline-method ac-start-tangent ac-true-color ac-visible ac-weights))

(mapcar #'make-slot (set-difference *acad-spline-properties* *acad-entity-properties*))