(defclass <acad-table> (<acad-entity>)
  (
  (ac-allow-manual-heights     :accessor ac-allow-manual-heights     :initarg :ac-allow-manual-heights     :initform nil :documentation "ac-allow-manual-heights")
  (ac-allow-manual-positions   :accessor ac-allow-manual-positions   :initarg :ac-allow-manual-positions   :initform nil :documentation "ac-allow-manual-positions")
  (ac-application              :accessor ac-application              :initarg :ac-application              :initform nil :documentation "ac-application")
  (ac-breaks-enabled           :accessor ac-breaks-enabled           :initarg :ac-breaks-enabled           :initform nil :documentation "ac-breaks-enabled")
  (ac-break-spacing            :accessor ac-break-spacing            :initarg :ac-break-spacing            :initform nil :documentation "ac-break-spacing")
  (ac-columns                  :accessor ac-columns                  :initarg :ac-columns                  :initform nil :documentation "ac-columns")
  (ac-column-width             :accessor ac-column-width             :initarg :ac-column-width             :initform nil :documentation "ac-column-width")
  (ac-direction                :accessor ac-direction                :initarg :ac-direction                :initform nil :documentation "ac-direction")
  (ac-document                 :accessor ac-document                 :initarg :ac-document                 :initform nil :documentation "ac-document")
  (ac-enable-break             :accessor ac-enable-break             :initarg :ac-enable-break             :initform nil :documentation "ac-enable-break")
  (ac-entity-transparency      :accessor ac-entity-transparency      :initarg :ac-entity-transparency      :initform nil :documentation "ac-entity-transparency")
  (ac-flow-direction           :accessor ac-flow-direction           :initarg :ac-flow-direction           :initform nil :documentation "ac-flow-direction")
  (ac-handle                   :accessor ac-handle                   :initarg :ac-handle                   :initform nil :documentation "ac-handle")
  (ac-has-extension-dictionary :accessor ac-has-extension-dictionary :initarg :ac-has-extension-dictionary :initform nil :documentation "ac-has-extension-dictionary")
  (ac-has-sub-selection        :accessor ac-has-sub-selection        :initarg :ac-has-sub-selection        :initform nil :documentation "ac-has-sub-selection")
  (ac-header-suppressed        :accessor ac-header-suppressed        :initarg :ac-header-suppressed        :initform nil :documentation "ac-header-suppressed")
  (ac-height                   :accessor ac-height                   :initarg :ac-height                   :initform nil :documentation "ac-height")
  (ac-horz-cell-margin         :accessor ac-horz-cell-margin         :initarg :ac-horz-cell-margin         :initform nil :documentation "ac-horz-cell-margin")
  (ac-hyperlinks               :accessor ac-hyperlinks               :initarg :ac-hyperlinks               :initform nil :documentation "ac-hyperlinks")
  (ac-insertion-point          :accessor ac-insertion-point          :initarg :ac-insertion-point          :initform nil :documentation "ac-insertion-point")
  (ac-layer                    :accessor ac-layer                    :initarg :ac-layer                    :initform nil :documentation "ac-layer")
  (ac-linetype                 :accessor ac-linetype                 :initarg :ac-linetype                 :initform nil :documentation "ac-linetype")
  (ac-linetype-scale           :accessor ac-linetype-scale           :initarg :ac-linetype-scale           :initform nil :documentation "ac-linetype-scale")
  (ac-lineweight               :accessor ac-lineweight               :initarg :ac-lineweight               :initform nil :documentation "ac-lineweight")
  (ac-material                 :accessor ac-material                 :initarg :ac-material                 :initform nil :documentation "ac-material")
  (ac-minimum-table-height     :accessor ac-minimum-table-height     :initarg :ac-minimum-table-height     :initform nil :documentation "ac-minimum-table-height")
  (ac-minimum-table-width      :accessor ac-minimum-table-width      :initarg :ac-minimum-table-width      :initform nil :documentation "ac-minimum-table-width")
  (ac-object-id                :accessor ac-object-id                :initarg :ac-object-id                :initform nil :documentation "ac-object-id")
  (ac-object-name              :accessor ac-object-name              :initarg :ac-object-name              :initform nil :documentation "ac-object-name")
  (ac-owner-id                 :accessor ac-owner-id                 :initarg :ac-owner-id                 :initform nil :documentation "ac-owner-id")
  (ac-plot-style-name          :accessor ac-plot-style-name          :initarg :ac-plot-style-name          :initform nil :documentation "ac-plot-style-name")
  (ac-regenerate-table-suppressed :accessor ac-regenerate-table-suppressed :initarg :ac-regenerate-table-suppressed :initform nil :documentation "ac-regenerate-table-suppressed")
  (ac-repeat-bottom-labels     :accessor ac-repeat-bottom-labels     :initarg :ac-repeat-bottom-labels     :initform nil :documentation "ac-repeat-bottom-labels")
  (ac-repeat-top-labels        :accessor ac-repeat-top-labels        :initarg :ac-repeat-top-labels        :initform nil :documentation "ac-repeat-top-labels")
  (ac-row-height               :accessor ac-row-height               :initarg :ac-row-height               :initform nil :documentation "ac-row-height")
  (ac-rows                     :accessor ac-rows                     :initarg :ac-rows                     :initform nil :documentation "ac-rows")
  (ac-style-name               :accessor ac-style-name               :initarg :ac-style-name               :initform nil :documentation "ac-style-name")
  (ac-table-break-flow-direction :accessor ac-table-break-flow-direction :initarg :ac-table-break-flow-direction :initform nil :documentation "ac-table-break-flow-direction")
  (ac-table-break-height       :accessor ac-table-break-height       :initarg :ac-table-break-height       :initform nil :documentation "ac-table-break-height")
  (ac-table-style-overrides    :accessor ac-table-style-overrides    :initarg :ac-table-style-overrides    :initform nil :documentation "ac-table-style-overrides")
  (ac-title-suppressed         :accessor ac-title-suppressed         :initarg :ac-title-suppressed         :initform nil :documentation "ac-title-suppressed")
  (ac-true-color               :accessor ac-true-color               :initarg :ac-true-color               :initform nil :documentation "ac-true-color")
  (ac-vert-cell-margin         :accessor ac-vert-cell-margin         :initarg :ac-vert-cell-margin         :initform nil :documentation "ac-vert-cell-margin")
  (ac-visible                  :accessor ac-visible                  :initarg :ac-visible                  :initform nil :documentation "ac-visible")
  (ac-width                    :accessor ac-width                    :initarg :ac-width                    :initform nil :documentation "ac-width")
  )
  (:documentation "AutoCAD table object."))

(defparameter *acad-table-properties* '(ac-allow-manual-heights ac-allow-manual-positions ac-application ac-breaks-enabled ac-break-spacing ac-columns ac-column-width ac-direction ac-document ac-enable-break ac-entity-transparency ac-flow-direction ac-handle ac-has-extension-dictionary ac-has-sub-selection ac-header-suppressed ac-height ac-horz-cell-margin ac-hyperlinks ac-insertion-point ac-layer ac-linetype ac-linetype-scale ac-lineweight ac-material ac-minimum-table-height ac-minimum-table-width ac-object-id ac-object-name ac-owner-id ac-plot-style-name ac-regenerate-table-suppressed ac-repeat-bottom-labels ac-repeat-top-labels ac-row-height ac-rows ac-style-name ac-table-break-flow-direction ac-table-break-height ac-table-style-overrides ac-title-suppressed ac-true-color ac-vert-cell-margin ac-visible ac-width))

(mapcar #'dxf/utils:make-slot (set-difference *acad-table-properties* *acad-entity-properties*))
