(defclass acad-point-cloud (acad-entity)
  (
  (ac-application              :accessor ac-application              :initarg :ac-application              :initform nil :documentation "ac-application")
  (ac-document                 :accessor ac-document                 :initarg :ac-document                 :initform nil :documentation "ac-document")
  (ac-entity-transparency      :accessor ac-entity-transparency      :initarg :ac-entity-transparency      :initform nil :documentation "ac-entity-transparency")
  (ac-handle                   :accessor ac-handle                   :initarg :ac-handle                   :initform nil :documentation "ac-handle")
  (ac-has-extension-dictionary :accessor ac-has-extension-dictionary :initarg :ac-has-extension-dictionary :initform nil :documentation "ac-has-extension-dictionary")
  (ac-height                   :accessor ac-height                   :initarg :ac-height                   :initform nil :documentation "ac-height")
  (ac-hyperlinks               :accessor ac-hyperlinks               :initarg :ac-hyperlinks               :initform nil :documentation "ac-hyperlinks")
  (ac-insertion-point          :accessor ac-insertion-point          :initarg :ac-insertion-point          :initform nil :documentation "ac-insertion-point")
  (ac-intensity-color-scheme   :accessor ac-intensity-color-scheme   :initarg :ac-intensity-color-scheme   :initform nil :documentation "ac-intensity-color-scheme")
  (ac-layer                    :accessor ac-layer                    :initarg :ac-layer                    :initform nil :documentation "ac-layer")
  (ac-length                   :accessor ac-length                   :initarg :ac-length                   :initform nil :documentation "ac-length")
  (ac-linetype                 :accessor ac-linetype                 :initarg :ac-linetype                 :initform nil :documentation "ac-linetype")
  (ac-linetype-scale           :accessor ac-linetype-scale           :initarg :ac-linetype-scale           :initform nil :documentation "ac-linetype-scale")
  (ac-lineweight               :accessor ac-lineweight               :initarg :ac-lineweight               :initform nil :documentation "ac-lineweight")
  (ac-locked                   :accessor ac-locked                   :initarg :ac-locked                   :initform nil :documentation "ac-locked")
  (ac-material                 :accessor ac-material                 :initarg :ac-material                 :initform nil :documentation "ac-material")
  (ac-name                     :accessor ac-name                     :initarg :ac-name                     :initform nil :documentation "ac-name")
  (ac-object-id                :accessor ac-object-id                :initarg :ac-object-id                :initform nil :documentation "ac-object-id")
  (ac-object-name              :accessor ac-object-name              :initarg :ac-object-name              :initform nil :documentation "ac-object-name")
  (ac-owner-id                 :accessor ac-owner-id                 :initarg :ac-owner-id                 :initform nil :documentation "ac-owner-id")
  (ac-path                     :accessor ac-path                     :initarg :ac-path                     :initform nil :documentation "ac-path")
  (ac-plot-style-name          :accessor ac-plot-style-name          :initarg :ac-plot-style-name          :initform nil :documentation "ac-plot-style-name")
  (ac-rotation                 :accessor ac-rotation                 :initarg :ac-rotation                 :initform nil :documentation "ac-rotation")
  (ac-scale                    :accessor ac-scale                    :initarg :ac-scale                    :initform nil :documentation "ac-scale")
  (ac-show-clipped             :accessor ac-show-clipped             :initarg :ac-show-clipped             :initform nil :documentation "ac-show-clipped")
  (ac-show-intensity           :accessor ac-show-intensity           :initarg :ac-show-intensity           :initform nil :documentation "ac-show-intensity")
  (ac-stylization              :accessor ac-stylization              :initarg :ac-stylization              :initform nil :documentation "ac-stylization")
  (ac-true-color               :accessor ac-true-color               :initarg :ac-true-color               :initform nil :documentation "ac-true-color")
  (ac-unit                     :accessor ac-unit                     :initarg :ac-unit                     :initform nil :documentation "ac-unit")
  (ac-unit-factor              :accessor ac-unit-factor              :initarg :ac-unit-factor              :initform nil :documentation "ac-unit-factor")
  (ac-use-entity-color         :accessor ac-use-entity-color         :initarg :ac-use-entity-color         :initform nil :documentation "ac-use-entity-color")
  (ac-visible                  :accessor ac-visible                  :initarg :ac-visible                  :initform nil :documentation "ac-visible")
  (ac-width                    :accessor ac-width                    :initarg :ac-width                    :initform nil :documentation "ac-width")
  )
  (:documentation "A source of point cloud content."))

(defparameter *acad-point-cloud-properties* '(ac-application ac-document ac-entity-transparency ac-handle ac-has-extension-dictionary ac-height ac-hyperlinks ac-insertion-point ac-intensity-color-scheme ac-layer ac-length ac-linetype ac-linetype-scale ac-lineweight ac-locked ac-material ac-name ac-object-id ac-object-name ac-owner-id ac-path ac-plot-style-name ac-rotation ac-scale ac-show-clipped ac-show-intensity ac-stylization ac-true-color ac-unit ac-unit-factor ac-use-entity-color ac-visible ac-width))

(mapcar #'make-slot (set-difference *acad-point-cloud-properties* *acad-entity-properties*))